apiVersion: v1
kind: Pod
metadata:
  name: xxx
spec:
  containers:
  - image: xxx
    name: xxx
    volumeMounts:
    - mountPath: /cache
      # name对应后面volumes里面定义的name
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}